# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026 Meizu Technologies

Syntax 4

SectionUseCase."HiFi" {
	File "/Qualcomm/sm8550/HiFi.conf"
	Comment "HiFi playback"
}

SectionUseCase."Voice Call" {
	File "/Qualcomm/sm8550/VoiceCall.conf"
	Comment "Make a phone call"
}

BootSequence [
	cset "name='RX_RX0 Digital Volume' 84"
	cset "name='RX_RX1 Digital Volume' 84"
	cset "name='HPHL Volume' 20"
	cset "name='HPHR Volume' 20"
	cset "name='RX_COMP1 Switch' 0"
	cset "name='RX_COMP2 Switch' 0"
]

LibraryConfig.remap.Config {
	ctl.default.map {
		"name='HP Volume'" {
			"name='HPHL Volume'".vindex.0 0
			"name='HPHR Volume'".vindex.1 0
		}
	}
}

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"
