# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026 Meizu Technologies

SectionVerb {
	EnableSequence [
		cset "name='SECONDARY_MI2S_RX Audio Mixer MultiMedia1' 1,1"
		cset "name='MultiMedia3 Mixer TX_CODEC_DMA_TX_3' 1"
	]

	DisableSequence [
		cset "name='SECONDARY_MI2S_RX Audio Mixer MultiMedia1' 0,0"
		cset "name='MultiMedia3 Mixer TX_CODEC_DMA_TX_3' 0"
	]

	Value.TQ "Voice"
}

SectionDevice."Earpiece" {
	Comment "Built-in earpiece"

	ConflictingDevice [
		"Speaker"
	]

	EnableSequence [
		cset "name='TFA Profile' receiver"
		cset "name='TFA Stop' 0,0"
	]

	DisableSequence [
		cset "name='TFA Stop' 1,1"
	]

	Value {
		PlaybackPriority 500
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
		PlaybackRate 48000
	}
}

SectionDevice."Speaker" {
	Comment "Built-in stereo speakers"

	ConflictingDevice [
		"Earpiece"
	]

	EnableSequence [
		cset "name='TFA Profile' speaker"
		cset "name='TFA Stop' 0,0"
	]

	DisableSequence [
		cset "name='TFA Stop' 1,1"
	]

	Value {
		PlaybackPriority 300
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
		PlaybackRate 48000
	}
}

SectionDevice."Mic" {
	Comment "Built-in microphone"

	Include.wcdmic1e.File "/codecs/wcd938x/AnalogMic1EnableSeq.conf"
	Include.wcdmic1d.File "/codecs/wcd938x/AnalogMic1DisableSeq.conf"
	Include.txmic1e.File "/codecs/qcom-lpass/tx-macro/SoundwireMic0EnableSeq.conf"
	Include.txmic1d.File "/codecs/qcom-lpass/tx-macro/SoundwireMicDisableSeq.conf"

	Value {
		CapturePriority 200
		CapturePCM "hw:${CardId},2"
		CaptureChannels 2
		CaptureRate 48000
		CaptureMixerElem "ADC1"
	}
}
